services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendOnly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo # Ensure mongo is up before the app starts
    environment:
      - MONGO_URI=mongodb://mongo:27017/ # Add this to pass the connection string
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  redis_data:
  node_modules:
